sudo: false
language: node_js
addons:
  postgresql: '9.4'
cache:
  directories:
    - node_modules
node_js:
  - '5'
  - '4'
before_script:
  - npm prune
script:
  - gulp
  - cd integration-test && ./run.sh
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
